<?php

/**
 * Perform alterations before an entity form is included in the IEF widget.
 *
 * @param $entity_form
 *   Nested array of form elements that comprise the entity form.
 * @param $form_state
 *   The form state of the parent form.
 */
function nrel_ecleds_implementing_mechanism_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  if ($entity_form['#bundle'] == 'activity') {
    $entity_form['#element_validate'][] = '_nrel_ecleds_implementing_activity_inline_form_validate';
  } elseif ($entity_form['#bundle'] == 'ecleds_results') {
    //dsm($entity_form);
    //dsm($form_state);
  }
}

function _nrel_ecleds_implementing_activity_inline_form_validate($entity_form, &$form_state) {
    $lang = $form_state['values']['language'];
    //dsm($form_state);
    foreach($form_state['values']['field_activities_ent_ref'][$lang]['form']['field_activity_indicator'][$lang] as $index => $field_indicator) {
      // skip loop if key is add_more
      if ($index === 'add_more') {
        continue;
      }
      $fiscal_year_string = $field_indicator['field_fiscal_year'][$lang][0]['value'];
      if ((6 != strlen($fiscal_year_string)) || ('FY' !== substr($fiscal_year_string, 0, 2))) {
        form_set_error('field_activities_ent_ref][' . $lang . '][form][field_activity_indicator][' . $lang . '][' . $index .'][field_fiscal_year', t('The fiscal year must be in the form "FY####".'));
      } else {
        $fiscal_year = substr($fiscal_year_string, 2, 4);
        if (!is_numeric($fiscal_year) || (4 != strlen(trim($fiscal_year)))) {
          form_set_error('field_activities_ent_ref][' . $lang . '][' . $index . '][field_fiscal_year', t('The fiscal year must be in the form "FY####".'));
        }
      }
    }
}
