
<?php

/**
 * Implements hook_init().
 */
function nrel_ecleds_custom_init() {
  // Cyber requested that we add in the X-Frame-Options header. Adding it to the
  // httpd.conf file breaks the filefield upload functionality. Here we add
  // X-Frame-Options: Deny to all but the path that handles the filefield .
  if (FALSE === strpos($path, 'file/ajax/')) {
    drupal_add_http_header('X-Frame-Options', 'DENY');
  }

  // Cyber requested stronger caching. This effectively causes browsers to do no
  // caching after 10 minutes, so if we see a performance hit, this may be the
  // first thing to look at changing.
  drupal_add_http_header('Cache-Control', 'no-cache, must-revalidate, pre-check=600, post-check=300, max-age=600, s-maxage=0');

}