<?php
/**
 * @file
 * ecleds_gcc_standard_indicator_field_collection_feature.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function ecleds_gcc_standard_indicator_field_collection_feature_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'field_bundle_settings_field_collection_item__field_impl_mech_gcc_indicator';
  $strongarm->value = array(
    'view_modes' => array(
      'full' => array(
        'custom_settings' => FALSE,
      ),
      'diff_standard' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(),
    ),
  );
  $export['field_bundle_settings_field_collection_item__field_impl_mech_gcc_indicator'] = $strongarm;

  return $export;
}
